export const PLATFORMS = Object.freeze({
  TRANSIENT: "transient",
  WIC: "wic1w",
  SSI: "ssi1w",
  MEDICAID: "medicaid1w",
  MEDICAL: "medical1w",
  CALFRESH: "calfresh1w",
  SNAP: "snap1w",
  EBT: "ebt1w",
  CALIFORNIA: "california",
  A_MAIN: "main",
  MAIN: "main1w",
  BYOP_1W: "byop1w",
  SIM_1W: "sim1w",
  TRIBAL: "tribal",
  GETLIFELINE: "getlifeline",
  GOVERNMENT_BENEFIT: "gov1w",
  TELECOM_ENROLLMENT_PARTNER: "excstep",
  TELECOM_PARTNER: "excstp",
  HISPANIC: "hispanic1w",
  INFINITI_MOBILE: "infinitiex",
});

export const TESTING_PLATFORMS = Object.freeze({
  LIFELINE: "lifeline",
  SNAP: "snap",
  MEDICAID: "medicaid",
  MEDICAL: "medical1w",
  CALFRESH: "calfresh1w",
  WIC: "wic",
  SSI: "ssi",
  EBT: "ebt",
  CALIFORNIA: "california",
  BYOP_1W: "byop1w",
  SIM_1W: "sim1w",
  TRIBAL: "tribal",
  GETLIFELINE: "getlifeline",
  LIHEAP: "liheap",
  NSL: "nsl",
  TANF: "tanf",
  GOVERNMENT_BENEFIT: "government",
  TELECOM_ENROLLMENT_PARTNER: "telecom_enrollment_partner",
  TELECOM_PARTNER: "telecom_partner",
  HISPANIC: "hispanic",
  INFINITI_MOBILE: "infinitimobile",
});

export const PATHS_URL = Object.freeze({
  ENROLLMENT_COMPLETED: "/form/enrollment-completed",
  ALREADY_ENROLLED: "/form/already-enrolled",
  ACTIVE_ACCOUNT: "/form/active-account",
  ACTIVE_FIELD_ACCOUNT: "/form/active-field-account",
  FREE_PHONE_NEXT_MONTH:
    "https://enrollmentpartnerexcess.sales-hub.com/free-phone-next-month",
  TRANSFER_BENEFITS:
    "https://enrollmentpartnerexcess.sales-hub.com/form/transfer-benefits",
  FREE_PHONE: "https://enrollmentpartnerexcess.sales-hub.com/free-phone",
  NOT_ELIGIBLE: "/form/not-eligible",
  UPDATE_INFORMATION:
    "https://enrollmentpartnerexcess.sales-hub.com/form/update-information",
  NV_PENDING: "/form/nv-validation",
  FREE_PHONE_QUALIFY: "/form/free-phone-qualify",
  ENROLLMENT_UNDER_REVIEW: "/form/enrollment-under-review",
  ENROLLMENT_IN_PROGRESS: "/under-review",
  WELCOME_BACK: "/keep-my-service/welcome-back",
  SUCCESS: "/success",
  CONFIRM_CONSENTS: "/keep-my-service/confirm-consents",
  SERVICE_CANCELLED: "/keep-my-service/service-cancelled",
  PAYMENT: "/payment",
  TECHNICAL_ISSUES: "/technical-issues",
  PAID_PHONE_OFFERING: "/paid-phone-offering",
  EOM: "/locked",
  LIFELINE: "excess.1wireless.com",
  WIC: "-wic",
  SSI: "-ssi",
  MEDICAID: "-medicaid",
  SNAP: "-snap",
  EBT: "-ebt",
  MAIN: "excessenrollment",
  CALIFORNIA: "excess-ca",
  MEDICAL: "excess-medical",
  CALFRESH: "excess-calfresh",
  BYOP: "-byop",
  SIM: "-sim",
  EXISTING_APPLICATION: "/existing-application",
  DENIED_PLAN_NOT_AVAILABLE: "/denied-plan-not-available",
  SELECT_PRODUCT: "/select-product",
  CALIFORNIA_PROOF_UPLOAD: "/upload-document",
  CALIFORNIA_PROOF_UPLOAD_CAPTURE: "/upload-document/capture",
  CALIFORNIA_PROOF_UPLOAD_CONFIRMATION: "/upload-document/confirmation",
  UPLOAD_STEPS: "/upload-steps",
  UNDER_REVIEW: "/under-review",
  CALIFORNIA_PROOF_ERROR: "/proof-error",
  MEDICAL_ID_WRONG: "/form/medical-wrong-number?order_id=",
  TRIBAL: "-tribal",
  GREAT_NEWS: "/great-news",
  GETLIFELINE: "-getlifeline",
  HISPANIC: "-esp",
  HOUSEHOLD_WORKSHEET: "/household-worksheet",
  GOVERNMENT_BENEFIT: "-gov",
  TELECOM_ENROLLMENT_PARTNER: "excesstelecomenrollmentpartner.com",
  TELECOM_PARTNER: "excesstelecompartner.com",
  INFINITI_MOBILE: "infinitimobilepartner.com",
});
