import AppProvider from "@/providers/app.provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import BrandLocale from "@/components/common/brand-locales";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Excess Telecom",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale = "en" } = await params;
	return (
		<html lang={locale}>
			<head>
				<link rel="shortcut icon" href="/favicon.ico" sizes="any" />
				<link rel="icon" href="/favicon.ico" sizes="any" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AppProvider locale={locale}>
					<BrandLocale />
					{children}
				</AppProvider>
			</body>
		</html>
	);
}
